### PR TITLE
Darken statusline text color for inactive splits

### PR DESCRIPTION
**Pull request by nkantar**
I'm really liking the color scheme, but I found the statusbar text color to be the same for active and inactive splits:
nova-statusline-before

I rely a lot on them being different to tell which split I'm in, so I changed the inactive split's statusbar text color to "background":
screen shot 2017-01-03 at 3 35 11 pm

I'm finding it very helpful, and others might as well.

### CODE REVIEW

**Comment by zanglg** [comment]
I think background is too dark to read the text. 
Maybe inconspicuous  is better.

**Comment by nkantar** [comment]
I'm having a hard time distinguishing "inconspicuous" from "foreground". What about one of the defined colors?

**Comment by nkantar** [comment]
I'll try experimenting and posting some screenshots for comparison.

**Comment by zanglg** [comment]
I have double checked my color, I found StatusLine and StatusLineNC has a attribute bold and reverse. I think it would looks same as you screenshot. Am I right ?

**Comment by nkantar** [comment]
For some reason mine isn't showing up as such, possibly due to not having a bold font available—I'll have to check this out a bit more thoroughly tomorrow.

I'm also testing this option out and so far it looks OK to me:
nova-orange-foreground

It's "orange" for active and "foreground" for inactive.

**Comment by zanglg** [comment]
statusline now has a color(lime) for active. check again.

**Comment by nkantar** [comment]
Most excellent—thanks so much for the responsiveness!

**Pull request closed without merging**
